// <auto-generated/>
// Auto-generated added to suppress names errors.

namespace UIWidgets
{
	using UnityEngine;
	using UnityEngine.EventSystems;
	using UnityEngine.UI;

	/// <summary>
	/// Button advanced. You can add callback on PointerEnter/Exit/Down/Up.
	/// </summary>
	public class ButtonAdvanced : Button,
		IPointerDownHandler, IPointerUpHandler,
		IPointerEnterHandler, IPointerExitHandler
	{
		/// <summary>
		/// What to do when the event system send a pointer down Event.
		/// </summary>
		[SerializeField]
		public PointerUnityEvent onPointerDown = new PointerUnityEvent();

		/// <summary>
		/// What to do when the event system send a pointer up Event.
		/// </summary>
		[SerializeField]
		public PointerUnityEvent onPointerUp = new PointerUnityEvent();

		/// <summary>
		/// What to do when the event system send a pointer enter Event.
		/// </summary>
		[SerializeField]
		public PointerUnityEvent onPointerEnter = new PointerUnityEvent();

		/// <summary>
		/// What to do when the event system send a pointer exit Event.
		/// </summary>
		[SerializeField]
		public PointerUnityEvent onPointerExit = new PointerUnityEvent();

		/// <summary>
		/// Process the pointer down event.
		/// </summary>
		/// <param name="eventData">Current event data.</param>
		public override void OnPointerDown(PointerEventData eventData)
		{
			onPointerDown.Invoke(eventData);
			base.OnPointerDown(eventData);
		}

		/// <summary>
		/// Process the pointer up event.
		/// </summary>
		/// <param name="eventData">Current event data.</param>
		public override void OnPointerUp(PointerEventData eventData)
		{
			onPointerUp.Invoke(eventData);
			base.OnPointerUp(eventData);
		}

		/// <summary>
		/// Process the pointer enter event.
		/// </summary>
		/// <param name="eventData">Current event data.</param>
		public override void OnPointerEnter(PointerEventData eventData)
		{
			onPointerEnter.Invoke(eventData);
			base.OnPointerEnter(eventData);
		}

		/// <summary>
		/// Process the pointer exit event.
		/// </summary>
		/// <param name="eventData">Current event data.</param>
		public override void OnPointerExit(PointerEventData eventData)
		{
			onPointerExit.Invoke(eventData);
			base.OnPointerExit(eventData);
		}
	}
}