// This file is provided under The MIT License as part of Steamworks.NET.
// Copyright (c) 2013-2022 Riley Labrecque
// Please see the included LICENSE.txt for additional information.

// This file is automatically generated.
// Changes to this file will be reverted when you update Steamworks.NET

#if !(UNITY_STANDALONE_WIN || UNITY_STANDALONE_LINUX || UNITY_STANDALONE_OSX || STEAMWORKS_WIN || STEAMWORKS_LIN_OSX)
	#define DISABLESTEAMWORKS
#endif

#if !DISABLESTEAMWORKS

using System.Runtime.InteropServices;
using IntPtr = System.IntPtr;

namespace Steamworks {
	[System.Serializable]
	public struct SteamLeaderboardEntries_t : System.IEquatable<SteamLeaderboardEntries_t>, System.IComparable<SteamLeaderboardEntries_t> {
		public ulong m_SteamLeaderboardEntries;

		public SteamLeaderboardEntries_t(ulong value) {
			m_SteamLeaderboardEntries = value;
		}

		public override string ToString() {
			return m_SteamLeaderboardEntries.ToString();
		}

		public override bool Equals(object other) {
			return other is SteamLeaderboardEntries_t && this == (SteamLeaderboardEntries_t)other;
		}

		public override int GetHashCode() {
			return m_SteamLeaderboardEntries.GetHashCode();
		}

		public static bool operator ==(SteamLeaderboardEntries_t x, SteamLeaderboardEntries_t y) {
			return x.m_SteamLeaderboardEntries == y.m_SteamLeaderboardEntries;
		}

		public static bool operator !=(SteamLeaderboardEntries_t x, SteamLeaderboardEntries_t y) {
			return !(x == y);
		}

		public static explicit operator SteamLeaderboardEntries_t(ulong value) {
			return new SteamLeaderboardEntries_t(value);
		}

		public static explicit operator ulong(SteamLeaderboardEntries_t that) {
			return that.m_SteamLeaderboardEntries;
		}

		public bool Equals(SteamLeaderboardEntries_t other) {
			return m_SteamLeaderboardEntries == other.m_SteamLeaderboardEntries;
		}

		public int CompareTo(SteamLeaderboardEntries_t other) {
			return m_SteamLeaderboardEntries.CompareTo(other.m_SteamLeaderboardEntries);
		}
	}
}

#endif // !DISABLESTEAMWORKS
