PlayAnimation(3, 6342, 6348);
jyx2_SwitchRoleAnimation("NPC/suxinghe", "Assets/BuildSource/AnimationControllers/KneelController.controller");
Talk(52, "逍遥派不肖弟子苏星河，拜见本派新任掌门。", "talkname52", 0);
Talk(49, "老前辈行此大礼，可折杀小僧了。", "talkname49", 0);
Talk(52, "师弟，你是我师父的关门弟子，又是本派掌门。我虽是师兄，却也要向你磕头！", "talkname52", 0);
Talk(49, "这个……这个……", "talkname49", 0);
Talk(52, "师父叫你拜他为师，要你磕九个头，你磕了没有？", "talkname52", 0);
Talk(49, "头是磕过的，不过当时我不知道是拜师。我是少林派弟子，不能改入别派。", "talkname49", 0);
Talk(52, "师父当然也想到了这一点，他老人家定是化去了你原来的武功，再传你本派功夫。师父已将毕生功力都传给了你，是不是？", "talkname52", 0);
Talk(49, "是的。", "talkname49", 0);
Talk(52, "象征本派掌门人的那枚宝石指环，是师父从自己手上除下来，给你戴在手上的，是不是？", "talkname52", 0);
Talk(49, "是！不过……不过我实在不知道这是什么掌门人的信物。", "talkname49", 0);
Talk(52, "师弟，你真是福泽深厚。我和丁春秋想这宝石指环，想了几十年，始终都无法到手，你却在一个时辰之内，便受到师父的垂青。", "talkname52", 0);
Talk(49, "前辈拿去便是。这只指环，小僧半点用处也没有。", "talkname49", 0);
Talk(52, "师弟，你受师父临死时的重托，岂能推卸责任？师父将指环交给你，是叫你除灭丁春秋那厮，是不是？", "talkname52", 0);
Talk(49, "正是。但小僧功行浅薄，怎能当此重任？", "talkname49", 0);
Talk(0, "贤弟，想不到你得到了个大奖，当起掌门来了。", "talkname0", 1);
Talk(49, "大哥，我……", "talkname49", 0);
ModifyEvent(-2, -2, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
do return end;
